name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests and generate Jacoco report
        run: ./gradlew clean testDebugUnitTest jacocoTestReport

      - name: Upload JaCoCo report to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: htmlReport

      - name: Run Detekt
        run: ./gradlew detekt || echo "Detekt failed" > error.log

      - name: Install jq
        run: sudo apt-get install jq

      - name: Notify Discord on Success
        if: success()
        run: |
          CONTENT=$(cat review_info.txt)
          echo "Sending Success Message: $CONTENT"
          JSON_STRING=$( jq -n \
                          --arg msg "$CONTENT" \
                          '{content: $msg}' )
          curl -X POST -H "Content-Type: application/json" -d "$JSON_STRING" ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord on Error
        if: failure()
        run: |
          ERROR_MSG=$(cat error.log)
          FINAL_MSG="Ocorreu o seguinte erro na pipeline: $ERROR_MSG"
          echo "Sending Error Message: $FINAL_MSG"
          JSON_STRING=$( jq -n \
                          --arg msg "$FINAL_MSG" \
                          '{content: $msg}' )
          curl -X POST -H "Content-Type: application/json" -d "$JSON_STRING" ${{ secrets.DISCORD_WEBHOOK_URL }}
        shell: bash

